import { mkdir } from 'node:fs/promises';
import { basename, join } from 'node:path';
import { readSkillMd, serializeSkillMd } from '../core/skill-parser.js';
import { writeText } from '../utils/fs-helpers.js';
import type { CompositionRequest, CompositionResult, ParsedSkill } from '../types/index.js';
import { buildAttributionLines } from './attribution.js';
import { mergeBodies, mergeFrontmatter, mergeStrategyDescription } from './merge.js';

function buildGeneratedBody(name: string, task?: string): string {
  return [
    `# ${name}`,
    '',
    '## Purpose',
    task ? `This skill was generated for the task: ${task}` : 'This skill was generated without a specific task description.',
    '',
    '## Suggested Workflow',
    '1. Inspect the current repo or inputs',
    '2. Execute the task with the minimum necessary tools',
    '3. Report findings clearly and concisely',
  ].join('\n');
}

function buildReadme(name: string, sources: string[], task?: string): string {
  return [
    `# ${name}`,
    '',
    'Generated by `skill-master compose`.',
    '',
    '## Task',
    task ?? 'Not provided',
    '',
    '## Sources',
    ...(sources.length > 0 ? sources.map((source) => `- ${source}`) : ['- Generated from task only']),
    '',
    '## Notes',
    '- Review `SKILL.md` before installation',
    '- Review `ATTRIBUTION.md` for provenance',
    '- Add supporting files if the merged skill requires scripts or templates',
    '',
  ].join('\n');
}

function buildSuggestedConfig(frontmatterAllowedTools: string[], envKeys: string[]): string {
  return [
    '# Suggested Configuration',
    '',
    `Allowed tools: ${frontmatterAllowedTools.length > 0 ? frontmatterAllowedTools.join(', ') : 'none declared'}`,
    `Environment keys: ${envKeys.length > 0 ? envKeys.join(', ') : 'none'}`,
    '',
    'Review and adapt these settings for your target agent runtime.',
    '',
  ].join('\n');
}

export async function composeSkills(request: CompositionRequest): Promise<CompositionResult> {
  await mkdir(request.outputDir, { recursive: true });
  const sourceDirs = request.sources ?? [];
  const parsed: ParsedSkill[] = [];

  for (const source of sourceDirs) {
    const skill = await readSkillMd(source);
    if (skill) parsed.push(skill);
  }

  const skillName = basename(request.outputDir);
  const frontmatter = parsed.length > 0
    ? mergeFrontmatter(parsed, skillName)
    : {
        name: skillName,
        description: request.task ? `Generated for task: ${request.task}` : 'Generated skill',
        'allowed-tools': [],
        'user-invocable': true,
      };

  const body = parsed.length > 0
    ? mergeBodies(parsed)
    : buildGeneratedBody(frontmatter.name, request.task);

  const skillMd = serializeSkillMd({
    frontmatter,
    body,
    rawFrontmatter: '',
  });

  const readmePath = join(request.outputDir, 'README.md');
  const attributionPath = join(request.outputDir, 'ATTRIBUTION.md');
  const configPath = join(request.outputDir, 'SUGGESTED_CONFIG.md');
  const sourcesPath = join(request.outputDir, 'SOURCES.md');
  const skillPath = join(request.outputDir, 'SKILL.md');

  await writeText(skillPath, skillMd);
  await writeText(readmePath, buildReadme(frontmatter.name, sourceDirs, request.task));
  await writeText(attributionPath, ['# Attribution', '', ...buildAttributionLines(sourceDirs), ''].join('\n'));
  await writeText(
    configPath,
    buildSuggestedConfig(frontmatter['allowed-tools'] ?? [], parsed.flatMap((skill) => skill.frontmatter['argument-hint'] ? [skill.frontmatter['argument-hint'] as string] : [])),
  );
  await writeText(
    sourcesPath,
    ['# Sources', '', ...(sourceDirs.length > 0 ? sourceDirs.map((source) => `- ${source}`) : ['- Generated from task only'])].join('\n') + '\n',
  );

  return {
    outputDir: request.outputDir,
    files: [skillPath, readmePath, attributionPath, configPath, sourcesPath],
    summary: [
      `Mode: ${request.mode}`,
      `Sources: ${sourceDirs.length}`,
      ...mergeStrategyDescription(sourceDirs.map((source) => basename(source))),
      `Output: ${request.outputDir}`,
    ],
    sources: sourceDirs,
  };
}
