import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdirSync, rmSync, writeFileSync, existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { composeSkills } from '../../src/compose/generate.js';

describe('composition', () => {
  let testDir: string;

  beforeEach(() => {
    testDir = join(tmpdir(), `skill-master-compose-test-${Date.now()}`);
    mkdirSync(join(testDir, 'skill-a'), { recursive: true });
    writeFileSync(join(testDir, 'skill-a', 'SKILL.md'), `---\nname: skill-a\ndescription: skill A\nallowed-tools:\n  - Read\n---\n# A\n`, 'utf-8');
  });

  afterEach(() => {
    rmSync(testDir, { recursive: true, force: true });
  });

  it('writes composed output package files', async () => {
    const outputDir = join(testDir, 'output');
    const result = await composeSkills({
      mode: 'merge',
      outputDir,
      sources: [join(testDir, 'skill-a')],
    });

    expect(result.files.length).toBeGreaterThan(0);
    expect(existsSync(join(outputDir, 'SKILL.md'))).toBe(true);
    expect(existsSync(join(outputDir, 'SOURCES.md'))).toBe(true);
    expect(existsSync(join(outputDir, 'README.md'))).toBe(true);
    expect(existsSync(join(outputDir, 'ATTRIBUTION.md'))).toBe(true);
    expect(existsSync(join(outputDir, 'SUGGESTED_CONFIG.md'))).toBe(true);
    expect(readFileSync(join(outputDir, 'README.md'), 'utf-8')).toContain('Generated by `skill-master compose`');
  });
});
