import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdirSync, rmSync, writeFileSync, existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { composeSkills } from '../../src/compose/generate.js';

describe('composition', () => {
  let testDir: string;

  beforeEach(() => {
    testDir = join(tmpdir(), `skill-master-compose-test-${Date.now()}`);
    mkdirSync(join(testDir, 'skill-a'), { recursive: true });
    writeFileSync(join(testDir, 'skill-a', 'SKILL.md'), `---\nname: skill-a\ndescription: skill A\nversion: 1.0.0\nauthor: upstream\nwebsite: https://example.com\nlicense: MIT\nallowed-tools:\n  - Read\n---\n# A\n`, 'utf-8');
  });

  afterEach(() => {
    rmSync(testDir, { recursive: true, force: true });
  });

  it('writes composed output package files', async () => {
    const outputDir = join(testDir, 'output');
    const result = await composeSkills({
      mode: 'merge',
      outputDir,
      sources: [join(testDir, 'skill-a')],
    });

    expect(result.files.length).toBeGreaterThan(0);
    expect(existsSync(join(outputDir, 'SKILL.md'))).toBe(true);
    expect(existsSync(join(outputDir, 'SOURCES.md'))).toBe(true);
    expect(existsSync(join(outputDir, 'README.md'))).toBe(true);
    expect(existsSync(join(outputDir, 'ATTRIBUTION.md'))).toBe(true);
    expect(existsSync(join(outputDir, 'SUGGESTED_CONFIG.md'))).toBe(true);
    expect(readFileSync(join(outputDir, 'README.md'), 'utf-8')).toContain('Generated by `skill-master compose`');
    const skillMd = readFileSync(join(outputDir, 'SKILL.md'), 'utf-8');
    expect(skillMd).not.toContain('author:');
    expect(skillMd).not.toContain('version:');
    expect(skillMd).not.toContain('website:');
    expect(skillMd).not.toContain('capabilities:');
  });

  it('writes OpenAI image API files and env contract from the task', async () => {
    const outputDir = join(testDir, 'image-api-output');
    const result = await composeSkills({
      mode: 'generate',
      outputDir,
      task: 'Generate images with gpt-image-2 through a third-party OpenAI-compatible API at http://localhost:3688/v1',
    });

    expect(result.files).toContain(join(outputDir, '.env.example'));
    expect(result.files).toContain(join(outputDir, 'scripts', 'gpt-image-2-api.mjs'));
    expect(readFileSync(join(outputDir, '.env.example'), 'utf-8')).toContain('OPENAI_API_KEY=');
    expect(readFileSync(join(outputDir, '.env.example'), 'utf-8')).toContain('OPENAI_BASE_URL=http://localhost:3688/v1');
    const skillMd = readFileSync(join(outputDir, 'SKILL.md'), 'utf-8');
    expect(skillMd).toContain('OPENAI_BASE_URL');
    expect(skillMd).not.toContain('author:');
    expect(skillMd).not.toContain('version:');
    expect(skillMd).not.toContain('capabilities:');
    expect(skillMd).not.toContain('Composed skill');
    expect(skillMd).not.toContain('Reference Skills');
  });
});
